/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author ideadPadGaming3i
 */
public class PrincipalWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalWindow.class.getName());

    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Cad = new javax.swing.JMenu();
        CadHosp = new javax.swing.JMenu();
        CadHospCad = new javax.swing.JMenuItem();
        CadHospCon = new javax.swing.JMenuItem();
        CadQuar = new javax.swing.JMenu();
        CadQuarCad = new javax.swing.JMenuItem();
        CadQuarCon = new javax.swing.JMenuItem();
        CadFunc = new javax.swing.JMenu();
        CadFuncCad = new javax.swing.JMenuItem();
        CadFuncCon = new javax.swing.JMenuItem();
        CadForn = new javax.swing.JMenu();
        CadFornCad = new javax.swing.JMenuItem();
        CadFornCon = new javax.swing.JMenuItem();
        CadProd = new javax.swing.JMenu();
        CadProdCad = new javax.swing.JMenuItem();
        CadProdCon = new javax.swing.JMenuItem();
        CadServ = new javax.swing.JMenu();
        CadServCad = new javax.swing.JMenuItem();
        CadServCon = new javax.swing.JMenuItem();
        Reserva = new javax.swing.JMenu();
        ReservaCad = new javax.swing.JMenuItem();
        ReservaCon = new javax.swing.JMenuItem();
        ReservaFin = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenu();
        VenProd = new javax.swing.JMenuItem();
        VenServ = new javax.swing.JMenuItem();
        Financeiro = new javax.swing.JMenu();
        FinCont = new javax.swing.JMenu();
        FinContCad = new javax.swing.JMenuItem();
        FinContCon = new javax.swing.JMenuItem();
        FinContRec = new javax.swing.JMenu();
        FinContRecCad = new javax.swing.JMenuItem();
        FinContRecCon = new javax.swing.JMenuItem();
        FinContBal = new javax.swing.JMenuItem();
        Relat = new javax.swing.JMenu();
        RelatFinan = new javax.swing.JMenu();
        RelatFinanCont = new javax.swing.JMenuItem();
        RelatFinanRece = new javax.swing.JMenuItem();
        RelatFinanBal = new javax.swing.JMenuItem();
        RelatReser = new javax.swing.JMenu();
        RelatReserQuarDisp = new javax.swing.JMenuItem();
        RelatReserQuarOcup = new javax.swing.JMenuItem();
        RelatReserFut = new javax.swing.JMenuItem();
        RelatVend = new javax.swing.JMenu();
        RelatVendProd = new javax.swing.JMenuItem();
        RelatVendServ = new javax.swing.JMenuItem();
        RelatVendTot = new javax.swing.JMenuItem();
        RelatHosp = new javax.swing.JMenuItem();
        RelatFunc = new javax.swing.JMenuItem();
        RelatForn = new javax.swing.JMenuItem();
        Seg = new javax.swing.JMenu();
        SegBackup = new javax.swing.JMenuItem();
        SegRest = new javax.swing.JMenuItem();
        Ferramentas = new javax.swing.JMenu();
        FerramentasTelaFundo = new javax.swing.JMenu();
        FerramentasTelaFundoAddImg = new javax.swing.JMenuItem();
        FerramentasTelaFundoRemImg = new javax.swing.JMenuItem();
        FerramentasTelaFundoRestPad = new javax.swing.JMenuItem();
        FerramentasSobreSistema = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenu();

        jMenu20.setText("File");
        jMenuBar2.add(jMenu20);

        jMenu21.setText("Edit");
        jMenuBar2.add(jMenu21);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Sistema Desenvolvido por Augusto da Costa Pires");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Cad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgCadastros.png"))); // NOI18N
        Cad.setText("Cadastros   |");
        Cad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadHosp.setText("Hospedes");
        CadHosp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadHospCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadHospCad.setText("Cadastrar");
        CadHospCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadHospCadActionPerformed(evt);
            }
        });
        CadHosp.add(CadHospCad);

        CadHospCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadHospCon.setText("Consultar");
        CadHosp.add(CadHospCon);

        Cad.add(CadHosp);

        CadQuar.setText("Quartos");
        CadQuar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadQuarCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadQuarCad.setText("Cadastrar");
        CadQuarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadQuarCadActionPerformed(evt);
            }
        });
        CadQuar.add(CadQuarCad);

        CadQuarCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadQuarCon.setText("Consultar");
        CadQuar.add(CadQuarCon);

        Cad.add(CadQuar);

        CadFunc.setText("Funcionários");
        CadFunc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadFuncCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadFuncCad.setText("Cadastrar");
        CadFuncCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadFuncCadActionPerformed(evt);
            }
        });
        CadFunc.add(CadFuncCad);

        CadFuncCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadFuncCon.setText("Consultar");
        CadFunc.add(CadFuncCon);

        Cad.add(CadFunc);

        CadForn.setText("Fornecedores");
        CadForn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadFornCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadFornCad.setText("Cadastrar");
        CadFornCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadFornCadActionPerformed(evt);
            }
        });
        CadForn.add(CadFornCad);

        CadFornCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadFornCon.setText("Consultar");
        CadForn.add(CadFornCon);

        Cad.add(CadForn);

        CadProd.setText("Produtos");
        CadProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadProdCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadProdCad.setText("Cadastrar");
        CadProdCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadProdCadActionPerformed(evt);
            }
        });
        CadProd.add(CadProdCad);

        CadProdCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadProdCon.setText("Consultar");
        CadProd.add(CadProdCon);

        Cad.add(CadProd);

        CadServ.setText("Serviços");
        CadServ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        CadServCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadServCad.setText("Cadastrar");
        CadServCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadServCadActionPerformed(evt);
            }
        });
        CadServ.add(CadServCad);

        CadServCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CadServCon.setText("Consultar");
        CadServ.add(CadServCon);

        Cad.add(CadServ);

        Menu.add(Cad);

        Reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgReservas.png"))); // NOI18N
        Reserva.setText("Reservas   |");
        Reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ReservaCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReservaCad.setText("Cadastrar Reserva");
        ReservaCad.setToolTipText("");
        ReservaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaCadActionPerformed(evt);
            }
        });
        Reserva.add(ReservaCad);

        ReservaCon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReservaCon.setText("Consultar Reserva");
        ReservaCon.setToolTipText("");
        ReservaCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaConActionPerformed(evt);
            }
        });
        Reserva.add(ReservaCon);

        ReservaFin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReservaFin.setText("Finalizar Reserva");
        ReservaFin.setToolTipText("");
        ReservaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservaFinActionPerformed(evt);
            }
        });
        Reserva.add(ReservaFin);

        Menu.add(Reserva);

        Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgVendas.png"))); // NOI18N
        Vendas.setText("Vendas   |");
        Vendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vendas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        VenProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VenProd.setText("Produtos");
        VenProd.setToolTipText("");
        VenProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenProdActionPerformed(evt);
            }
        });
        Vendas.add(VenProd);

        VenServ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VenServ.setText("Serviços");
        VenServ.setToolTipText("");
        VenServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenServActionPerformed(evt);
            }
        });
        Vendas.add(VenServ);

        Menu.add(Vendas);

        Financeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgFinanceiro.png"))); // NOI18N
        Financeiro.setText("Financeiro   |");
        Financeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Financeiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FinCont.setText("Contas a Pagar");
        FinCont.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FinContCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FinContCad.setText("Cadastrar");
        FinContCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinContCadActionPerformed(evt);
            }
        });
        FinCont.add(FinContCad);

        FinContCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FinContCon.setText("Consultar");
        FinCont.add(FinContCon);

        Financeiro.add(FinCont);

        FinContRec.setText("Contas a Receber");
        FinContRec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FinContRecCad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FinContRecCad.setText("Cadastrar");
        FinContRecCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinContRecCadActionPerformed(evt);
            }
        });
        FinContRec.add(FinContRecCad);

        FinContRecCon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FinContRecCon.setText("Consultar");
        FinContRec.add(FinContRecCon);

        Financeiro.add(FinContRec);

        FinContBal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FinContBal.setText("Balanço");
        FinContBal.setToolTipText("");
        FinContBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinContBalActionPerformed(evt);
            }
        });
        Financeiro.add(FinContBal);

        Menu.add(Financeiro);

        Relat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgRelatório.png"))); // NOI18N
        Relat.setText("Relatórios   |");
        Relat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Relat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        RelatFinan.setText("Financeiro");
        RelatFinan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        RelatFinanCont.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatFinanCont.setText("Contas a Pagar");
        RelatFinanCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatFinanContActionPerformed(evt);
            }
        });
        RelatFinan.add(RelatFinanCont);

        RelatFinanRece.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatFinanRece.setText("Contas a Receber");
        RelatFinan.add(RelatFinanRece);

        RelatFinanBal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatFinanBal.setText("Balanço");
        RelatFinan.add(RelatFinanBal);

        Relat.add(RelatFinan);

        RelatReser.setText("Reservas");
        RelatReser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        RelatReserQuarDisp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatReserQuarDisp.setText("Quartos Disponiveis");
        RelatReserQuarDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatReserQuarDispActionPerformed(evt);
            }
        });
        RelatReser.add(RelatReserQuarDisp);

        RelatReserQuarOcup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatReserQuarOcup.setText("Quartos Ocupados");
        RelatReser.add(RelatReserQuarOcup);

        RelatReserFut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatReserFut.setText("Reservas Futuras");
        RelatReserFut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatReserFutActionPerformed(evt);
            }
        });
        RelatReser.add(RelatReserFut);

        Relat.add(RelatReser);

        RelatVend.setText("Vendas");
        RelatVend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        RelatVendProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatVendProd.setText("Produtos");
        RelatVendProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatVendProdActionPerformed(evt);
            }
        });
        RelatVend.add(RelatVendProd);

        RelatVendServ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatVendServ.setText("Serviços");
        RelatVend.add(RelatVendServ);

        RelatVendTot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RelatVendTot.setText("Total");
        RelatVend.add(RelatVendTot);

        Relat.add(RelatVend);

        RelatHosp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RelatHosp.setText("Hospedes");
        RelatHosp.setToolTipText("");
        RelatHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatHospActionPerformed(evt);
            }
        });
        Relat.add(RelatHosp);

        RelatFunc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RelatFunc.setText("Funcionários");
        RelatFunc.setToolTipText("");
        RelatFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatFuncActionPerformed(evt);
            }
        });
        Relat.add(RelatFunc);

        RelatForn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RelatForn.setText("Fornecedores");
        RelatForn.setToolTipText("");
        RelatForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatFornActionPerformed(evt);
            }
        });
        Relat.add(RelatForn);

        Menu.add(Relat);

        Seg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgSegurança.png"))); // NOI18N
        Seg.setText("Segurança   |");
        Seg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SegBackup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SegBackup.setText("Fazer Backup");
        SegBackup.setToolTipText("");
        SegBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegBackupActionPerformed(evt);
            }
        });
        Seg.add(SegBackup);

        SegRest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SegRest.setText("Restaurar Sistema");
        SegRest.setToolTipText("");
        SegRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegRestActionPerformed(evt);
            }
        });
        Seg.add(SegRest);

        Menu.add(Seg);

        Ferramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgFerramentas.png"))); // NOI18N
        Ferramentas.setText("Ferramentas   |");
        Ferramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ferramentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FerramentasTelaFundo.setText("Tela de Fundo");
        FerramentasTelaFundo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FerramentasTelaFundoAddImg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FerramentasTelaFundoAddImg.setText("Adicionar Imagem");
        FerramentasTelaFundoAddImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FerramentasTelaFundoAddImgActionPerformed(evt);
            }
        });
        FerramentasTelaFundo.add(FerramentasTelaFundoAddImg);

        FerramentasTelaFundoRemImg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FerramentasTelaFundoRemImg.setText("Remover Imagem");
        FerramentasTelaFundo.add(FerramentasTelaFundoRemImg);

        FerramentasTelaFundoRestPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FerramentasTelaFundoRestPad.setText("Restaurar para o Padrão");
        FerramentasTelaFundo.add(FerramentasTelaFundoRestPad);

        Ferramentas.add(FerramentasTelaFundo);

        FerramentasSobreSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FerramentasSobreSistema.setText("Sobre o Sistema");
        FerramentasSobreSistema.setToolTipText("");
        FerramentasSobreSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FerramentasSobreSistemaActionPerformed(evt);
            }
        });
        Ferramentas.add(FerramentasSobreSistema);

        Menu.add(Ferramentas);

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgSair.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Menu.add(Sair);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(371, 371, 371))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 325, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadHospCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadHospCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadHospCadActionPerformed

    private void CadQuarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadQuarCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadQuarCadActionPerformed

    private void CadFuncCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFuncCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadFuncCadActionPerformed

    private void CadFornCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFornCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadFornCadActionPerformed

    private void CadProdCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadProdCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadProdCadActionPerformed

    private void CadServCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadServCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadServCadActionPerformed

    private void ReservaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservaCadActionPerformed

    private void ReservaConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservaConActionPerformed

    private void ReservaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReservaFinActionPerformed

    private void VenProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenProdActionPerformed

    private void VenServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenServActionPerformed

    private void FinContBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinContBalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinContBalActionPerformed

    private void FinContRecCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinContRecCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinContRecCadActionPerformed

    private void FinContCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinContCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinContCadActionPerformed

    private void RelatFinanContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatFinanContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatFinanContActionPerformed

    private void RelatReserQuarDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatReserQuarDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatReserQuarDispActionPerformed

    private void RelatVendProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatVendProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatVendProdActionPerformed

    private void RelatHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatHospActionPerformed

    private void RelatFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatFuncActionPerformed

    private void RelatFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatFornActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatFornActionPerformed

    private void RelatReserFutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatReserFutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatReserFutActionPerformed

    private void SegBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegBackupActionPerformed

    private void SegRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegRestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegRestActionPerformed

    private void FerramentasTelaFundoAddImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FerramentasTelaFundoAddImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FerramentasTelaFundoAddImgActionPerformed

    private void FerramentasSobreSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FerramentasSobreSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FerramentasSobreSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cad;
    private javax.swing.JMenu CadForn;
    private javax.swing.JMenuItem CadFornCad;
    private javax.swing.JMenuItem CadFornCon;
    private javax.swing.JMenu CadFunc;
    private javax.swing.JMenuItem CadFuncCad;
    private javax.swing.JMenuItem CadFuncCon;
    private javax.swing.JMenu CadHosp;
    private javax.swing.JMenuItem CadHospCad;
    private javax.swing.JMenuItem CadHospCon;
    private javax.swing.JMenu CadProd;
    private javax.swing.JMenuItem CadProdCad;
    private javax.swing.JMenuItem CadProdCon;
    private javax.swing.JMenu CadQuar;
    private javax.swing.JMenuItem CadQuarCad;
    private javax.swing.JMenuItem CadQuarCon;
    private javax.swing.JMenu CadServ;
    private javax.swing.JMenuItem CadServCad;
    private javax.swing.JMenuItem CadServCon;
    private javax.swing.JMenu Ferramentas;
    private javax.swing.JMenuItem FerramentasSobreSistema;
    private javax.swing.JMenu FerramentasTelaFundo;
    private javax.swing.JMenuItem FerramentasTelaFundoAddImg;
    private javax.swing.JMenuItem FerramentasTelaFundoRemImg;
    private javax.swing.JMenuItem FerramentasTelaFundoRestPad;
    private javax.swing.JMenu FinCont;
    private javax.swing.JMenuItem FinContBal;
    private javax.swing.JMenuItem FinContCad;
    private javax.swing.JMenuItem FinContCon;
    private javax.swing.JMenu FinContRec;
    private javax.swing.JMenuItem FinContRecCad;
    private javax.swing.JMenuItem FinContRecCon;
    private javax.swing.JMenu Financeiro;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Relat;
    private javax.swing.JMenu RelatFinan;
    private javax.swing.JMenuItem RelatFinanBal;
    private javax.swing.JMenuItem RelatFinanCont;
    private javax.swing.JMenuItem RelatFinanRece;
    private javax.swing.JMenuItem RelatForn;
    private javax.swing.JMenuItem RelatFunc;
    private javax.swing.JMenuItem RelatHosp;
    private javax.swing.JMenu RelatReser;
    private javax.swing.JMenuItem RelatReserFut;
    private javax.swing.JMenuItem RelatReserQuarDisp;
    private javax.swing.JMenuItem RelatReserQuarOcup;
    private javax.swing.JMenu RelatVend;
    private javax.swing.JMenuItem RelatVendProd;
    private javax.swing.JMenuItem RelatVendServ;
    private javax.swing.JMenuItem RelatVendTot;
    private javax.swing.JMenu Reserva;
    private javax.swing.JMenuItem ReservaCad;
    private javax.swing.JMenuItem ReservaCon;
    private javax.swing.JMenuItem ReservaFin;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenu Seg;
    private javax.swing.JMenuItem SegBackup;
    private javax.swing.JMenuItem SegRest;
    private javax.swing.JMenuItem VenProd;
    private javax.swing.JMenuItem VenServ;
    private javax.swing.JMenu Vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
