/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author ideadPadGaming3i
 */
public class PrincipalWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrincipalWindow.class.getName());

    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuCadHospede = new javax.swing.JMenuItem();
        menuConHospede = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuCadQuartos = new javax.swing.JMenuItem();
        menuConQuartos = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuCadFuncionario = new javax.swing.JMenuItem();
        menuConFuncionario = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuConFornecedores = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuCadProduto = new javax.swing.JMenuItem();
        menuConProduto = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        menuCadServico = new javax.swing.JMenuItem();
        menuConServico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadHospede1 = new javax.swing.JMenuItem();
        menuCadHospede2 = new javax.swing.JMenuItem();
        menuCadHospede3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCadHospede4 = new javax.swing.JMenuItem();
        menuCadHospede5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        menuCadHospede6 = new javax.swing.JMenuItem();
        menuConHospede1 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        menuCadHospede7 = new javax.swing.JMenuItem();
        menuConHospede2 = new javax.swing.JMenuItem();
        menuCadHospede8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        menuCadHospede9 = new javax.swing.JMenuItem();
        menuConHospede3 = new javax.swing.JMenuItem();
        menuConHospede6 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        menuCadHospede10 = new javax.swing.JMenuItem();
        menuConHospede4 = new javax.swing.JMenuItem();
        menuCadHospede15 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        menuCadHospede11 = new javax.swing.JMenuItem();
        menuConHospede5 = new javax.swing.JMenuItem();
        menuConHospede7 = new javax.swing.JMenuItem();
        menuCadHospede12 = new javax.swing.JMenuItem();
        menuCadHospede13 = new javax.swing.JMenuItem();
        menuCadHospede14 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuCadHospede16 = new javax.swing.JMenuItem();
        menuCadHospede17 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        menuCadHospede18 = new javax.swing.JMenuItem();
        menuConHospede8 = new javax.swing.JMenuItem();
        menuConHospede9 = new javax.swing.JMenuItem();
        menuCadHospede19 = new javax.swing.JMenuItem();
        windowPrinSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgCadastros.png"))); // NOI18N
        jMenu1.setText("Cadastros   |");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu9.setText("Hospedes");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede.setText("Cadastrar");
        menuCadHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospedeActionPerformed(evt);
            }
        });
        jMenu9.add(menuCadHospede);

        menuConHospede.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede.setText("Consultar");
        jMenu9.add(menuConHospede);

        jMenu1.add(jMenu9);

        jMenu10.setText("Quartos");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadQuartos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadQuartos.setText("Cadastrar");
        menuCadQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadQuartosActionPerformed(evt);
            }
        });
        jMenu10.add(menuCadQuartos);

        menuConQuartos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConQuartos.setText("Consultar");
        jMenu10.add(menuConQuartos);

        jMenu1.add(jMenu10);

        jMenu8.setText("Funcionários");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadFuncionario.setText("Cadastrar");
        menuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFuncionarioActionPerformed(evt);
            }
        });
        jMenu8.add(menuCadFuncionario);

        menuConFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConFuncionario.setText("Consultar");
        jMenu8.add(menuConFuncionario);

        jMenu1.add(jMenu8);

        jMenu12.setText("Fornecedores");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadFornecedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadFornecedores.setText("Cadastrar");
        menuCadFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedoresActionPerformed(evt);
            }
        });
        jMenu12.add(menuCadFornecedores);

        menuConFornecedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConFornecedores.setText("Consultar");
        jMenu12.add(menuConFornecedores);

        jMenu1.add(jMenu12);

        jMenu11.setText("Produtos");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadProduto.setText("Cadastrar");
        menuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutoActionPerformed(evt);
            }
        });
        jMenu11.add(menuCadProduto);

        menuConProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConProduto.setText("Consultar");
        jMenu11.add(menuConProduto);

        jMenu1.add(jMenu11);

        jMenu13.setText("Serviços");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadServico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadServico.setText("Cadastrar");
        menuCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadServicoActionPerformed(evt);
            }
        });
        jMenu13.add(menuCadServico);

        menuConServico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConServico.setText("Consultar");
        jMenu13.add(menuConServico);

        jMenu1.add(jMenu13);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgReservas.png"))); // NOI18N
        jMenu2.setText("Reservas   |");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede1.setText("Cadastrar Reserva");
        menuCadHospede1.setToolTipText("");
        menuCadHospede1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede1ActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadHospede1);

        menuCadHospede2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede2.setText("Consultar Reserva");
        menuCadHospede2.setToolTipText("");
        menuCadHospede2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede2ActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadHospede2);

        menuCadHospede3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede3.setText("Finalizar Reserva");
        menuCadHospede3.setToolTipText("");
        menuCadHospede3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede3ActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadHospede3);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgVendas.png"))); // NOI18N
        jMenu3.setText("Vendas   |");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede4.setText("Produtos");
        menuCadHospede4.setToolTipText("");
        menuCadHospede4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede4ActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadHospede4);

        menuCadHospede5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede5.setText("Serviços");
        menuCadHospede5.setToolTipText("");
        menuCadHospede5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede5ActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadHospede5);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgFinanceiro.png"))); // NOI18N
        jMenu4.setText("Financeiro   |");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu14.setText("Contas a Pagar");
        jMenu14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede6.setText("Cadastrar");
        menuCadHospede6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede6ActionPerformed(evt);
            }
        });
        jMenu14.add(menuCadHospede6);

        menuConHospede1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede1.setText("Consultar");
        jMenu14.add(menuConHospede1);

        jMenu4.add(jMenu14);

        jMenu15.setText("Contas a Receber");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede7.setText("Cadastrar");
        menuCadHospede7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede7ActionPerformed(evt);
            }
        });
        jMenu15.add(menuCadHospede7);

        menuConHospede2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede2.setText("Consultar");
        jMenu15.add(menuConHospede2);

        jMenu4.add(jMenu15);

        menuCadHospede8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede8.setText("Balanço");
        menuCadHospede8.setToolTipText("");
        menuCadHospede8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede8ActionPerformed(evt);
            }
        });
        jMenu4.add(menuCadHospede8);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgRelatório.png"))); // NOI18N
        jMenu5.setText("Relatórios   |");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu16.setText("Financeiro");
        jMenu16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede9.setText("Contas a Pagar");
        menuCadHospede9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede9ActionPerformed(evt);
            }
        });
        jMenu16.add(menuCadHospede9);

        menuConHospede3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede3.setText("Contas a Receber");
        jMenu16.add(menuConHospede3);

        menuConHospede6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede6.setText("Balanço");
        jMenu16.add(menuConHospede6);

        jMenu5.add(jMenu16);

        jMenu17.setText("Reservas");
        jMenu17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede10.setText("Quartos Disponiveis");
        menuCadHospede10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede10ActionPerformed(evt);
            }
        });
        jMenu17.add(menuCadHospede10);

        menuConHospede4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede4.setText("Quartos Ocupados");
        jMenu17.add(menuConHospede4);

        menuCadHospede15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede15.setText("Reservas Futuras");
        menuCadHospede15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede15ActionPerformed(evt);
            }
        });
        jMenu17.add(menuCadHospede15);

        jMenu5.add(jMenu17);

        jMenu18.setText("Vendas");
        jMenu18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede11.setText("Produtos");
        menuCadHospede11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede11ActionPerformed(evt);
            }
        });
        jMenu18.add(menuCadHospede11);

        menuConHospede5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede5.setText("Serviços");
        jMenu18.add(menuConHospede5);

        menuConHospede7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede7.setText("Total");
        jMenu18.add(menuConHospede7);

        jMenu5.add(jMenu18);

        menuCadHospede12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede12.setText("Hospedes");
        menuCadHospede12.setToolTipText("");
        menuCadHospede12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede12ActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadHospede12);

        menuCadHospede13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede13.setText("Funcionários");
        menuCadHospede13.setToolTipText("");
        menuCadHospede13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede13ActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadHospede13);

        menuCadHospede14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede14.setText("Fornecedores");
        menuCadHospede14.setToolTipText("");
        menuCadHospede14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede14ActionPerformed(evt);
            }
        });
        jMenu5.add(menuCadHospede14);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgSegurança.png"))); // NOI18N
        jMenu6.setText("Segurança   |");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede16.setText("Fazer Backup");
        menuCadHospede16.setToolTipText("");
        menuCadHospede16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede16ActionPerformed(evt);
            }
        });
        jMenu6.add(menuCadHospede16);

        menuCadHospede17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede17.setText("Restaurar Sistema");
        menuCadHospede17.setToolTipText("");
        menuCadHospede17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede17ActionPerformed(evt);
            }
        });
        jMenu6.add(menuCadHospede17);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/imgFerramentas.png"))); // NOI18N
        jMenu7.setText("Ferramentas   |");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu19.setText("Tela de Fundo");
        jMenu19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        menuCadHospede18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuCadHospede18.setText("Adicionar Imagem");
        menuCadHospede18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede18ActionPerformed(evt);
            }
        });
        jMenu19.add(menuCadHospede18);

        menuConHospede8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede8.setText("Remover Imagem");
        jMenu19.add(menuConHospede8);

        menuConHospede9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuConHospede9.setText("Restaurar para o Padrão");
        jMenu19.add(menuConHospede9);

        jMenu7.add(jMenu19);

        menuCadHospede19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuCadHospede19.setText("Sobre o Sistema");
        menuCadHospede19.setToolTipText("");
        menuCadHospede19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadHospede19ActionPerformed(evt);
            }
        });
        jMenu7.add(menuCadHospede19);

        jMenuBar1.add(jMenu7);

        windowPrinSair.setText("Sair");
        windowPrinSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(windowPrinSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospedeActionPerformed

    private void menuCadQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadQuartosActionPerformed

    private void menuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadFuncionarioActionPerformed

    private void menuCadFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadFornecedoresActionPerformed

    private void menuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadProdutoActionPerformed

    private void menuCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadServicoActionPerformed

    private void menuCadHospede1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede1ActionPerformed

    private void menuCadHospede2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede2ActionPerformed

    private void menuCadHospede3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede3ActionPerformed

    private void menuCadHospede4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede4ActionPerformed

    private void menuCadHospede5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede5ActionPerformed

    private void menuCadHospede8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede8ActionPerformed

    private void menuCadHospede7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede7ActionPerformed

    private void menuCadHospede6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede6ActionPerformed

    private void menuCadHospede9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede9ActionPerformed

    private void menuCadHospede10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede10ActionPerformed

    private void menuCadHospede11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede11ActionPerformed

    private void menuCadHospede12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede12ActionPerformed

    private void menuCadHospede13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede13ActionPerformed

    private void menuCadHospede14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede14ActionPerformed

    private void menuCadHospede15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede15ActionPerformed

    private void menuCadHospede16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede16ActionPerformed

    private void menuCadHospede17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede17ActionPerformed

    private void menuCadHospede18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede18ActionPerformed

    private void menuCadHospede19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadHospede19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadHospede19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrincipalWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadFuncionario;
    private javax.swing.JMenuItem menuCadHospede;
    private javax.swing.JMenuItem menuCadHospede1;
    private javax.swing.JMenuItem menuCadHospede10;
    private javax.swing.JMenuItem menuCadHospede11;
    private javax.swing.JMenuItem menuCadHospede12;
    private javax.swing.JMenuItem menuCadHospede13;
    private javax.swing.JMenuItem menuCadHospede14;
    private javax.swing.JMenuItem menuCadHospede15;
    private javax.swing.JMenuItem menuCadHospede16;
    private javax.swing.JMenuItem menuCadHospede17;
    private javax.swing.JMenuItem menuCadHospede18;
    private javax.swing.JMenuItem menuCadHospede19;
    private javax.swing.JMenuItem menuCadHospede2;
    private javax.swing.JMenuItem menuCadHospede3;
    private javax.swing.JMenuItem menuCadHospede4;
    private javax.swing.JMenuItem menuCadHospede5;
    private javax.swing.JMenuItem menuCadHospede6;
    private javax.swing.JMenuItem menuCadHospede7;
    private javax.swing.JMenuItem menuCadHospede8;
    private javax.swing.JMenuItem menuCadHospede9;
    private javax.swing.JMenuItem menuCadProduto;
    private javax.swing.JMenuItem menuCadQuartos;
    private javax.swing.JMenuItem menuCadServico;
    private javax.swing.JMenuItem menuConFornecedores;
    private javax.swing.JMenuItem menuConFuncionario;
    private javax.swing.JMenuItem menuConHospede;
    private javax.swing.JMenuItem menuConHospede1;
    private javax.swing.JMenuItem menuConHospede2;
    private javax.swing.JMenuItem menuConHospede3;
    private javax.swing.JMenuItem menuConHospede4;
    private javax.swing.JMenuItem menuConHospede5;
    private javax.swing.JMenuItem menuConHospede6;
    private javax.swing.JMenuItem menuConHospede7;
    private javax.swing.JMenuItem menuConHospede8;
    private javax.swing.JMenuItem menuConHospede9;
    private javax.swing.JMenuItem menuConProduto;
    private javax.swing.JMenuItem menuConQuartos;
    private javax.swing.JMenuItem menuConServico;
    private javax.swing.JMenu windowPrinSair;
    // End of variables declaration//GEN-END:variables
}
